### ISSUE TITLE
Speaker Scratchpad für Meetup "Azure News von der Build"

### ISSUE THREAD

**Issue by christophwille** [christophwille/meetupazurewien#3]
Jeder Speaker legt sich einen Comment zu dieser Issue an, und aktualisiert sie während / direkt nach der Build mit coolen und/oder für wichtig erachteten Themen. Und zwar nicht nur für Themen die man selbst machen will/kann, sondern die man eben allgemein für cool/wichtig erachtet (und ggf andere Speaker machen sollen/können). Damit nichts untergeht.

Ziel ist es, aus diesem Pool an Ideen dann die tatsächlichen Vorträge zu generieren.

**Comment by christophwille** [comment]
CWs comment on news

* Cloud Shell
* Mobile App
* MySQL / Postgres (Wordpress Demo?)
* VS 15.2 News: Functions, Logic, Snapshot Debugging (more?)
* Cosmos
* Azure IoT Edge


unsorted

Managed Instance Preview 4 SQL

AI News / Video Indexer
Graph / Project Rome

https://aka.ms/zipkin-azure
https://azure.microsoft.com/en-us/blog/introducing-azure-functions-runtime-preview/
https://github.com/aspnet/EntityFramework/wiki/Roadmap#ef-core-20-under-development
https://blogs.msdn.microsoft.com/webdev/2017/05/10/azure-function-tools-for-visual-studio-2017/
https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-beta.1
https://azure.microsoft.com/en-us/blog/microsoft-extends-azure-managed-database-services-with-introduction-of-mysql-and-postgresql/
Database mig service

Nicht separat rausgeklaubt aber der Azure Weekly hat auch ein paar tidbits:

http://campaigns.endjin.com/t/ViewEmailArchive/t/878369FA467039CB/C67FD2F38AC4859C/


plus weitere Summaries:

https://www.hanselman.com/blog/BUILD2017ConferenceRollupForNETDevelopers.aspx

https://sqlservercode.blogspot.co.at/2017/05/all-build-2017-data-related-sessions-in.html

https://www.heise.de/developer/artikel/Die-BUILD-Nachrichten-in-der-Kurzzusammenfassung-3715485.html

https://blogs.msdn.microsoft.com/dotnet/2017/05/16/the-week-in-net-microsoft-build-2017-net-core-2-0-preview-1-for-the-king/

DevOps
https://blogs.msdn.microsoft.com/visualstudioalm/2017/05/17/build-2017-recap/
https://edsquared.com/devops-at-microsoft-build-2017-c9b2d97bfca8

Non-Azure

https://matthijs.hoekstraonline.net/2017/05/18/build-2017-videos-from-windows-uwp/

**Comment by nmpollak** [comment]
VS2017 - Cross Docker Container Debugging
Container Services (running existing IIS/WCF Application)
Azure Dashboard - Container, Service Fabric and application data telemetry
Dockerimages natively in Azure App Service
Azure Functions Runtime
Application Insights with Azure Functions

**Comment by MEhrenmueller** [comment]
CosmosDB
Was - Warum - Wie

**Comment by christophwille** [comment]
Themenzuweisung an Speaker:

(ich erbe was auch immer überbleibt, if anything)

* Andi: Cosmos (mit Fokus Delta DocDb -> Cosmos, Gremlin)
* Markus: Mig Tool
* Toni: talk1: Logic Apps & PowerApps News, talk2: Graph News
* CWilfing: Admin (Cloud Shell & Mobile App)
* ChristianN: .NET Core Galore
* ...

**Comment by MEhrenmueller** [comment]
Würde mich bei CosmosDB gerne dazuhängen ... 
Ansonsten könnte ich was über das neue Azure Migration Tool erzählen (um Datenbanken nach Azure zu bringen)

**Comment by christophwille** [comment]
Mig tool wäre super dachte nicht dass das jemand nehmen würde wollen.

**Comment by christiannagel** [comment]
* Neue Cognitive Services
* Azure Stack
* Bot Framework, Bot Builder, Bot Services
* ASP.NET Core 2.0
* Azure Active Directory von UWP und ASP.NET Core

**Comment by christophwille** [comment]
@christiannagel nur Azure :-)

**Comment by christiannagel** [comment]
@christophwille hatte ich mit dem Co-Meetup anders verstanden, ist aber ok. Gibt mehr als genug zu Azure. Nur muss ich dann auch noch ein extra Meetup zur Build starten.

**Comment by christophwille** [comment]
@christiannagel zB (ASP).NET Core 2.0 hat Azure-Bezug (absolut!), und das Delta zu 1.x zu erklären und zu zeigen definitiv cool. (hätte es gleich besser formulieren sollen - "Azure-Bezug, nicht nur Azure-only")

**Comment by RStadlmair** [comment]
**@christophwille:** Hallo ! - Habe mir die Liste der Videos angesehen. Ausser einem Vortrag CI/CD ist nichts über PowerShell gesagt worden. Werde deshalb als Zuschauer kommen. PS6 und Azure-Shell gibt nicht ausreichend für 10 Minuten her.

**Comment by dennings** [comment]
@christiannagel: zu AzureStack könnten wir gerne etwas gemeinsam machen! Ich habe aktuelle Infos und auch 4 Server dafür ;) Ready for Demo. 
Bin leider nächste Woche auf AzureStack Zertifizierung in Paris, daher kann ich am Montag nicht dabei sein ;(

**Comment by christiannagel** [comment]
@dennings schade dass du nicht dabei sein kannst. Ich kann dazu nur Theorie erzählen. Kann aber gern weitergeben dass es von dir auch Demos gibt :-)

**Comment by christiannagel** [comment]
@christophwille ok, hab ASP.NET Core 2.0 wieder dazu geschrieben - Bezug wegen Deployment auf Azure? Damit würde aber auch C# wieder zutreffen - wird bei ASP.NET Core verwendet. Und UWP verwendet auch Azure...

**Comment by christophwille** [comment]
@christiannagel bei ASP.NET ist der Bezug automatisch da. Wenn Du einfach alles .NET Core 2.0 machst? Also ASP.NET, EF, die Verwirrung wg auf welcher Runtime das läuft, roadmaps, install bei current 15.3 preview, ....

**Comment by christiannagel** [comment]
@christophwille ok, passt. Ich mache alles zu .NET Core 2.0.

**Comment by StefanKoell** [comment]
@christophwille Hab' noch nicht viel Gelegenheit gehabt mir die Aufzeichnungen anzuschauen - bin aber diese Woche in der Schweiz und sollte genug Zeit haben was zu finden. Entweder Richtung DevOps oder richtung HighDPI support in WinForms/WPF - oder beides ;) Interessant?

**Comment by christophwille** [comment]
@StefanKoell Azure-related. DevOps wäre nach dieser Definition ok, WinForms eher nicht ;-)

**Comment by StefanKoell** [comment]
@christophwille LOL! Dachte ich mir ;)

Ich werde mich um einen 10 Minuten "Was gibt's neues im Bereich DevOps" bemühen, wenn's OK ist :)

**Comment by christophwille** [comment]
@StefanKoell Wenn das Sample ned grad eine WinForms app ist absolut :-)

**Comment by tonipohl** [comment]
1) SSO for Office Apps
2) PowerApps und LogicApps Neuigkeiten

**Comment by tonipohl** [comment]
3) Microsoft Graph News - ev. Christoph?
Weitere Themen-Vorschläge, die glaub ich noch nicht vorkamen - falls die wer machen möchte...
AppInsights, Cortana, IoT, die neue ML Vision API (ferns Demo), SPFx (SharePoint Framework Announcements), uvm, wer will? ;)

**Comment by pwahlmueller** [comment]
@christophwille Habe mir auch die Liste der Videos angesehen. Cognitive Services und AI fände ich interessant, befürchte aber, dass ich diese Woche nicht genug Zeit zur Vorbereitung dafür habe. Dh nimm' mich bitte von der Liste.

**Comment by christophwille** [comment]
@pwahlmueller done

**Comment by wolfgangstrasser** [comment]
Ich muss euch leider für Montag absagen - bin für einen Workshop eingeplant (am anderen Ende von Österreich) und kann nicht nach Wien kommen... sorry für die kurzfristige Absage..

**Comment by christophwille** [comment]
@tonipohl ok, wie wär' das Paket "Logic Apps & Power Apps News" für Dich. Passt zusammen, und mischt verschiedene target audiences.

**Comment by StefanKoell** [comment]
@christophwille Hey Chris! Hab' soeben erfahren, dass ich am Montag leider absagen muss :( Schade, wäre gerne dabei gewesen. Ich hoffe Du findest ein anderes "Opfer" bzgl. DevOps.

**Comment by tonipohl** [comment]
Ich könnte noch MSFT Graph machen...

**Comment by christophwille** [comment]
@tonipohl das wär dann aber sinnvollerweise ein zweiter 10 min Slot? Oder willst das zu Logic apps dazugeben???

**Comment by tonipohl** [comment]
2.ter slot

**Comment by christophwille** [comment]
ok, das nehm ich gern :-) wollte aufgrund des Speakerschwunds eh fragen ob jemand Zeit hat einen zweiten Slot vorzubereiten.

**Comment by tonipohl** [comment]
fein, passt.

**Comment by hannespreishuber** [comment]
so, hab mir nun den Termin freigeschaufelt und den Vorschlag von Chris aufgegriffen
Azure Functions + VS Tooling
@tonipohl  Abgrenzung Logic apps
bleibts bei 10 Min Lightning?

**Comment by christophwille** [comment]
Ja, 10 Minuten Lightning sind nach wie vor der Plan. Aber so wie Toni kann man einen zweiten Slot für ein weiteres Thema bekommen (aber nicht back-to-back, dh overflow oder "ich mach halt länger" nene)

**Comment by MEhrenmueller** [comment]
@Migration Service
Das ist leider nur in private preview - schwer zu sagen, ob ich da noch freigeschalten werde.
Slide-only wird da wenig hergeben. 
Ich würde daher dann noch auf weitere Azure DB-Features (Managed Instance (auch nur in private preview), SQL Database Advisor, Threat Detection, Automatic Tuning, etc.) eingehen.

**Comment by christophwille** [comment]
@MEhrenmueller ok, also "Data-News von der Build" (quasi alles außer Cosmos). Das können wir dann back-to-back mit @apollak Cosmos Slot nehmen.

**Comment by tonipohl** [comment]
Chris, nachdem ja nur 10 min für die Themen vorgesehen sind: PowerPoint und ev, fertige Mini-Demo sofern vorhanden?

**Comment by christophwille** [comment]
Ja, in zehn Minuten wird nicht viel Live-Coding reingehen. Facts, Einschätzungen sind wichtiger.
